### ISSUE TITLE
Could you please share script to decompose a C++ code into code lines as mentioned in the paper?

### ISSUE THREAD

**Issue by anks12297** [Sumith1896/spoc#3]
Hi, thanks for sharing your great work!

I have read your paper and it mentions that you decompose code into code lines with certain rule in Decomposition section. Could you please share script to decompose a C++ code into code lines as mentioned in the paper?

Thank you in advance!

**Comment by sumith1896** [comment]
Hi @anks12297,

Thank you for your interest! We basically decompose a code snippet into lines and allow simple higher-level constructs (such as single line conditional or loop) to also appear in a single line. This can be achieved with the clang-format script I just pushed here: https://github.com/Sumith1896/spoc/blob/master/scripts/clang-format-spoc. I hope that helps!
